import { randomUUID, randomBytes, createHash } from 'node:crypto';

/**
 * IDs are UUIDv4 and may be generated by either side. Offline clients mint their
 * own so a record created without a network keeps a stable identity once it
 * syncs, which is also what makes mutation replay idempotent.
 */
export function newId(): string {
  return randomUUID();
}

const UUID_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

export function isUuid(value: string): boolean {
  return UUID_PATTERN.test(value);
}

export function randomToken(bytes = 32): string {
  return randomBytes(bytes).toString('base64url');
}

export function sha256(input: string | Buffer): string {
  return createHash('sha256').update(input).digest('hex');
}
